google_client_id = "dummy-client-id-12345.apps.googleusercontent.com"
google_client_secret = "dummy-secret-67890"
base_url = "http://localhost:8501"
[gemini]
api_key = "AIzaSyAPbFkFJorVqyJfSDGvsSV8xHbw-k6zRCY"
google_client_id = "YOUR_GOOGLE_CLIENT_ID"
google_client_secret = "YOUR_GOOGLE_CLIENT_SECRET"
base_url = "http://localhost:8501"

edamam_app_id = "YOUR_EDAMAM_APP_ID"
edamam_app_key = "YOUR_EDAMAM_APP_KEY"
usda_api_key = "YOUR_USDA_API_KEY"
gemini_api_key = "YOUR_GEMINI_API_KEY"

twilio_sid = "YOUR_TWILIO_SID"
twilio_auth_token = "YOUR_TWILIO_AUTH_TOKEN"
twilio_sms_from = "+1XXXXXXXXXX"              # Twilio SMS number (E.164 format)
twilio_whatsapp_from = "whatsapp:+14155238886" # Twilio WhatsApp sandbox ya approved sender
